### PR TITLE
DP-9570 Remove raw filter from _patterns/01-atoms/08-lists/unordered-list.twig

### PR DESCRIPTION
**Pull request by ygannett**
Any PRs being created needs a changelog.txt file before being merged into dev. See: [Change Log Instructions](https://github.com/massgov/mayflower/blob/dev/docs/change-log-instructions.md)

## Description

Remove raw filter from _patterns/01-atoms/08-lists/unordered-list.twig.

Usage of the template in Mayflower
```
 ~/MassIT/mayflower/ [feature/DP-9570_atoms-lists-unordered-list] grep -r 'unordered-list.twig' patternlab/styleguide/source
patternlab/styleguide/source/_patterns/03-organisms/by-author/form-requirements-in-two-column.json:        "path": "@atoms/08-lists/unordered-list.twig",
patternlab/styleguide/source/_patterns/03-organisms/by-author/form-requirements.json:        "path": "@atoms/08-lists/unordered-list.twig",
patternlab/styleguide/source/_patterns/03-organisms/by-author/rich-text-description.json:      "path": "@atoms/08-lists/unordered-list.twig",
patternlab/styleguide/source/_patterns/03-organisms/by-author/rich-text.json:      "path": "@atoms/08-lists/unordered-list.twig",
patternlab/styleguide/source/_patterns/03-organisms/by-author/steps-unordered.json:          "path": "@atoms/08-lists/unordered-list.twig",
patternlab/styleguide/source/_patterns/04-templates/01-content-types/alert.json:          "path": "@atoms/08-lists/unordered-list.twig",
patternlab/styleguide/source/_patterns/04-templates/01-content-types/form-page.json:        "path": "@atoms/08-lists/unordered-list.twig",
patternlab/styleguide/source/_patterns/05-pages/event~end-date-with-time.json:        "path": "@atoms/08-lists/unordered-list.twig",
patternlab/styleguide/source/_patterns/05-pages/event~end-date.json:        "path": "@atoms/08-lists/unordered-list.twig",
patternlab/styleguide/source/_patterns/05-pages/guide.json:            "path": "@atoms/08-lists/unordered-list.twig",
patternlab/styleguide/source/_patterns/05-pages/guide.json:                    "path": "@atoms/08-lists/unordered-list.twig",
patternlab/styleguide/source/_patterns/05-pages/howto.json:        "path": "@atoms/08-lists/unordered-list.twig",
patternlab/styleguide/source/_patterns/05-pages/howto.json:        "path": "@atoms/08-lists/unordered-list.twig",
patternlab/styleguide/source/_patterns/05-pages/policy-advisory-directive.json:        "path": "@atoms/08-lists/unordered-list.twig",
patternlab/styleguide/source/_patterns/05-pages/site-alert.json:          "path": "@atoms/08-lists/unordered-list.twig",
 ~/MassIT/mayflower/ [feature/DP-9570_atoms-lists-unordered-list]
```

## Related Issue / Ticket

- [DP-9570](https://jira.mass.gov/browse/DP-9570)

## Steps to Test

1. Go to the following page type samples and see the areas the template is used have any display issues in both Mayflower and Drupal.

- Event:  You will need
- Guide:  section unit
- How-to:  main content area
- Advisory:  section unit
- Site-alert: Alert unit content

## Screenshots
Use something like [licecap](http://www.cockos.com/licecap/) to capture gifs to demonstrate behaviors.

## Additional Notes:

Anything else to add?

#### Impacted Areas in Application

* 

#### @TODO

*

### CODE REVIEW

**Comment by rbayliss** [comment]
Hey Yukiko,
This is actually another pattern that's not used in Drupal.  BUT, it does look like this change introduces some visual breakage.  See attached screenshot, which is displaying on this page: https://mayflower.digital.mass.gov/b/feature/DP-9570_atoms-lists-unordered-list/?p=organisms-steps-unordered.  

screen shot 2018-07-20 at 5 29 40 pm

This is the kind of breakage I've been expecting.  I believe we need to work around it by disabling twig auto escaping on the Pattern Lab side.  My reasoning here is that in Patternlab, we need to be able to pass in arbitrary HTML strings, which can't be marked as "safe", so we can't use Twig Autoescape.  On the Drupal side, we have the ability to mark strings as safe, so it shouldn't affect us.  I've created a branch demonstrating this change [here](https://github.com/massgov/mayflower/commit/080cbe26e31d6c22f77882b593b55bed2d7285c2) - can you pull this change into your branch and make sure it fixes the issue?  

CC'ing @tnathanjames for a sanity check on this.

**Comment by ygannett** [comment]
@rbayliss Thank you for your help.  I merged your branch to change the configuration.  Now, the link is rendered properly.
pattern_lab_-_viewall-organisms-all

**Review by rbayliss — APPROVED** [review]
This looks good to me! On to @mrossi113 for IR.  I don't believe this one touches Drupal in any way.

**Review by mrossi113 — APPROVED** [review]
👍 LGTM! S&M this PR!

**Pull request merged**
