### PR TITLE
DP-16804 State organizations link in Utility Nav

### PR DESCRIPTION
**Pull request by ygannett**
Any PRs being created needs a changelog.txt file before being merged into dev. See: [Change Log Instructions](https://github.com/massgov/mayflower/blob/dev/docs/change-log-instructions.md)

## Description

Change the state organizations menu from a button to a link directly to the page.

## Related Issue / Ticket

- [JIRA issue](https://jira.mass.gov/browse/DP-16804)

## Steps to Test

1. Go to any page in localhost:3000.
2. Check the State Organizations menu item in the Utility Nav in inspect.
3. Find the menu item is a link. Its href value is "#", not actual URL in Mayflower.
4. Do the step 3 and 4 in mobile display.
5. Pull the branch into Drupal and find the link href value has the URL to the state organizations page.

## Screenshots
Desktop
Pattern_Lab_-_pages-Homepage

Mobile
mobile

## Additional Notes:

Anything else to add?

#### Impacted Areas in Application

* 

#### @TODO

*

### CODE REVIEW

**Review by lynnschumann — CHANGES_REQUESTED** [review]
This worked fine when I pulled the branch into Drupal and tested. When I viewed the branch locally in Mayflower, "State Organizations" does not appear (confirmed this also at https://mayflower.digital.mass.gov/b/patternlab/DP-16804_state-organizations-link/index.html). This is because in patternlab/styleguide/source/_data/utilityNav.json, line 26, "links" is empty: 
` "links": ""`
Once I added an array of link info to utilityNav.json `"href": "#"`,  I can see "State Organizations" in the menu in Mayflower.

**Review by lynnschumann — CHANGES_REQUESTED** [review]
Update utilityNav.json to add "href": "#". Otherwise, looks good!

**Comment by ygannett** [comment]
@lynnschumann Thank you for the note.  utilityNav.json has been updated. Please review again.

**Review by lynnschumann — APPROVED** [review]
LGTM!

**Review by a-username — APPROVED** [review]
Good on my end as well

**Pull request merged**
