### PR TITLE
DP-29416 Change twigger .svg to X and add Threads .svg

### PR DESCRIPTION
**Pull request by weitzman**
## Related Issue / Ticket

https://massgov.atlassian.net/browse/DP-29416

### CODE REVIEW

**Comment by clairesunstudio** [comment]
Generally, we add the raw icon without a background color and with the default fill color for social media icons. They are styled using CSS. Sometimes without background, sometimes inverted. For examples:
Screen Shot 2023-08-30 at 3 52 42 PM
Screen Shot 2023-08-30 at 3 53 12 PM

**Comment by weitzman** [comment]
Thanks How do I get that from the images provided? See https://massgov.atlassian.net/browse/DP-29416

**Comment by clairesunstudio** [comment]
@weitzman They will need to be adjusted and re-exported in the design software. You can assign the tickets to me and I can work on them on Monday

**Comment by clairesunstudio** [comment]
replaced by #1836

**Pull request closed without merging**
