### PR TITLE
[Patternlab] DP-22679  Adjust focus order between the menu button and the menu container

### PR DESCRIPTION
**Pull request by ygannett**
…ve tabindex from the utility nav items when the menu closes.

Any PRs being created needs a changelog.txt file before being merged into dev. See: [Change Log Instructions](https://github.com/massgov/mayflower/blob/develop/docs/for-developers/changelog-instructions.md)

## Description

With screen width greater than 620 px, when the global nav menu opens, tabbing from the menu button sets focus on the Google translate instead of the first top level global nav item. Adjust the focus order by adding `tab-index="-1"` to the Google translate link to make the element unfocusable along with the rest of the utility nav items.

When the menu closes, tabindex remained with the utility nav items.  This prevented focus on them.  Set to remove those tabindex from the utility nav items as the menu closes.

In the menu container, set up focus trap, all visible menu items can get tab through then go back to the menu button.  While the dropdown is open, focus circles all visible menu items with **TAB** and **SHIFT + TAB**.

Set up to close Google Translate option container with ESC.  Wherever in the container, hitting ESC closes the option container and set focus on the Google Translate button.

## Related Issue / Ticket

- [JIRA issue1](https://massgov.atlassian.net/browse/DP-22679)
- [JIRA issue2](https://massgov.atlassian.net/browse/DP-22680)

## Steps to Test

1. Go to any page except for the home.
2. In screen width greater than 840px, tab to the menu button.  Open the menu with ENTER, then tab again. Find focus moves from the menu button to the first top level global nav item (Living), not on the Google translate.
3. Set focus on the menu button.  Hit ENTER to close the menu, then tab again.  Find focus moves from the menu button to the Google translate.  Keep tabbing and find focus moves through the rest of the utility nav items from left to right.
4. In screen width between 621px and 840px, tab to the menu button.  Open the menu with ENTER, then tab again. Find focus moves from the menu button to the first top level global nav item (Living).
4. In screen width less than 621px, tab to the menu button.  Open the menu with ENTER, then tab again. Find focus moves from the menu button to the Mass.gov logo.
5. In screen width less than 840px, find you can tab through all menu items, then circle back to the menu button.  **Shift + Tab** works in reversed direction.
6. In screen width greater than 840px, tab to Google Translate on the blue bar, hit ENTER to open the option container.  In the container, hit ESC.  Find the option container closes and the Google Translate button gets focus.
7. In screen width less than 841px, tab to Google Translate in the dropdown, hit ENTER to open the option container.  In the container, hit ESC.  Find the option container closes and the Google Translate button gets focus.

## Screenshots
Use something like [licecap](http://www.cockos.com/licecap/) to capture gifs to demonstrate behaviors.

## Additional Notes:

Anything else to add?

#### Impacted Areas in Application

*

#### @TODO

*

### CODE REVIEW

**Comment by clairesunstudio** [comment]
Since this PR was created before the focusTrapping function, can you update this to use that instead? I wonder if you think it makes sense to fix the main nav in this PR --> https://github.com/massgov/mayflower/pull/1489 or after this gets in?

**Comment by clairesunstudio** [comment]
A few issues noticed in external review:
>external UAT link --> https://mayflower.digital.mass.gov/patternlab/b/patternlab/DP-22679_globalnav-keyboard-nav/?p=pages-bio-page
1.  "Select Language" button in the mobile tray is not keyboard selectable, it gets skipped. 
>Screen Shot 2021-09-24 at 2 24 37 PM

>**Update**: this only is not working on hamburger menu other than on the homepage, the z-index is set to -1. 

2.  The only way to close the "Select Language" modal is to tab through all the language options (we know this is a problem we probably can't fix). However, tabbing through the last language option doesn't focus back onto the next item correctly and this is problematic. Can we add some custom JS to handle that? 

3. On mobile sizes, when there's a search button next to menu, the search button should be skipped, as we discussed and decided for the mayflower react component --> https://mayflower.digital.mass.gov/react/iframe.html?id=organisms-headerhamburger--header-hamburger-example&viewMode=story. Currently, the search icon is only focusable using TAB, but not SHIFT + TAB
```
// See the settings in mayflower react as reference:
      focusTrapping({
        focusableSelectors: '[role="menuitem"], .ma__utility-nav__link > a, .ma__utility-nav__item > button, .ma__utility-panel__item > span > a',
        closeButtonSelector: '.ma__header__hamburger__menu-button',
        modalSelector: '.ma__header__hamburger__nav-container',
        keyEvent: e
      });
```

4. The focus outline is a little hard to see on the menu button 
>Screen Shot 2021-09-24 at 2 23 58 PM

**Comment by ygannett** [comment]
The items 1, 3 and 4 have been fixed/modified.

**Comment by clairesunstudio** [comment]
Hi @ygannett, I can confirm that the search icon is being skipped now. 
But the language select is still not working for me for some reason:
http://localhost:3000/?p=pages-bio-page

I also tested it on the homepage (it is tabbable on the homepage), when someone selects it and tabs through all the options, the focus is lost. So I don't know if that's acceptable.

**Comment by ygannett** [comment]
The keyboard navigation for the Google Translate widget in the blue bar is set up.  Also, ESC to close the menu with the GT menu button in the hamburger menu is set up.  The GT menu button behaves same as other utility nav menu buttons.

**Review by clairesunstudio — APPROVED** [review]
looks good!

**Pull request merged**
