### PR TITLE
Fix vulnerability

### PR DESCRIPTION
**Pull request by clairesunstudio**
screen shot 2018-07-16 at 3 34 39 pm
auto fix npm vulnerabilities
To test: run `npm audit`

**before [patternlab]**
screen shot 2018-07-16 at 3 45 46 pm

**after [patternlab]**
screen shot 2018-07-17 at 9 41 43 am

**before [react]**
screen shot 2018-07-17 at 12 17 07 pm

**after [react]**
screen shot 2018-07-17 at 12 17 31 pm

### CODE REVIEW

**Comment by rbayliss** [comment]
Hmm, we've been using yarn to manage things on the Patternlab side.  Without a new `yarn.lock` file, I don't think it will invalidate our caching in Circle to use the new packages.  Do you want me to take care of that, or can you?

**Comment by clairesunstudio** [comment]
@rbayliss yes please! feel free to take over!

**Comment by rbayliss** [comment]
This actually isn't possible to fix at the moment - we're waiting on an upstream update in https://github.com/nodejs/node-gyp/pull/1471.  Once that's done, we can run `yarn upgrade` inside `patternlab/styleguide` to fix the issue.  In the meantime, I'm getting rid of our `package-lock.json`, which is outdated anyway.

**Comment by mrossi113** [comment]
@rbayliss do you want me to review this PR? So we are removing the package-lock.json in patternlab and updating the package.json/package.lock in react. Do we need to monitor for an upstream update in nodejs/node-gyp#1471 somewhere (maybe in the `mayflower/issues`?)

**Comment by rbayliss** [comment]
@mrossi113 - Let's leave it for now.  It's still in progress, since we haven't updated all of the vulnerable packages yet.

**Comment by mrjmd** [comment]
The `nwb` vulnerability looks legit, the update here looks good so far from the React component library side.

**Comment by rbayliss** [comment]
@mrjmd - is it enough of an issue that we should merge what's been done so far and follow up to get the other vulnerability later on?

**Comment by rbayliss** [comment]
I just checked back in on this, and the `hoek` vulnerability still isn't fixed.  It seems like we're in for a long wait here as upstream packages update things in response to the new `npm audit` stuff and github warnings.  I think we might just want to merge this as long as this build comes back green.  It won't fix all of our problems, but it will fix the majority, and we can follow up later on with another update.

On a side note, babelify needs an update on the Patternlab side.  This turns out to be complicated, since babel's made a lot of progress since Mayflower got started.  I'm gonna create a separate ticket just for that.

**Review by rbayliss — APPROVED** [review]
@clairesunstudio - This looks good to me.  I'm assuming we can go ahead and merge it now?  See my comments above - the `hoek` vulnerability still isn't fixed upstream, but I don't think we should wait on it any longer.

**Pull request merged**
