### PR TITLE
DP-9485 Update Mayflower release process with monorepo

### PR DESCRIPTION
**Pull request by mrossi113**
This some minor changes to the mayflower release process. I will need to wait for #25 to be merged into develop before updating links and having this ready to be reviewed. Need to discuss the communication release section to see if necessary for this repository.

### CODE REVIEW

**Comment by clairesunstudio** [comment]
@mrossi113 can you pr into #25 instead of develop and we can merge it in together?

**Comment by mrossi113** [comment]
Talked with @clairesunstudio about this PR. I still have to wait on a discussion about the communication release piece before this is ready to review. This should happen at tomorrow meeting.

**Comment by mrossi113** [comment]
@rbayliss if you could review this when you have a chance some link and procedural changes to release process.

**Review by rbayliss — APPROVED** [review]
@mrossi113 - This looks great!  I'll S+M now.

**Pull request merged**
