### PR TITLE
DP-9574 Remove raw filter from 02_molecules/google-map.twig

### PR DESCRIPTION
**Pull request by ygannett**
Any PRs being created needs a changelog.txt file before being merged into dev. See: [Change Log Instructions](https://github.com/massgov/mayflower/blob/dev/docs/change-log-instructions.md)

## Description

Remove raw filter from styleguide/source/_patterns/02-molecules/google-map.twig

Use of the template in Mayflower:
```
 ~/MassIT/mayflower/patternlab/ [feature/DP-9574_molecules-google-map] grep -r 'google-map.twig' styleguide/source
styleguide/source/_patterns/03-organisms/by-author/location-banner.twig:    {% include "@molecules/google-map.twig" %}
styleguide/source/_patterns/03-organisms/by-author/location-listing.twig:          {% include "@molecules/google-map.twig" %}
styleguide/source/_patterns/03-organisms/by-author/mapped-locations.twig:    {% include "@molecules/google-map.twig" %}
styleguide/source/_patterns/05-pages/location-general-content.twig:  {% include "@molecules/google-map.twig" %}
styleguide/source/_patterns/05-pages/location-park-content.twig:  {% include "@molecules/google-map.twig" %}
styleguide/source/assets/js/modules/googleMap.js:      const rawData = ma.googleMapData[i]; // Data object created in @molecules/google-map.twig
 ~/MassIT/mayflower/patternlab/ [feature/DP-9574_molecules-google-map]
```

## Related Issue / Ticket

- [DP-9574 Mayflower: Remove "raw" filter from 02-molecules/google-map.twig](https://jira.mass.gov/browse/DP-9574)

## Steps to Test

1. Go to the Location Listing page and check for any display issue with listing item info.
2. Go to the Location pages and check for any display issue with the banner map.

## Screenshots
Location Listing:
dp-9574_mf-location-listing

Location:
dp-9574_mf-location-banner

dp-9574_mf-location-general

## Additional Notes:

Anything else to add?

#### Impacted Areas in Application

* 

#### @TODO

*

### CODE REVIEW

**Comment by rbayliss** [comment]
Hey @ygannett - This PR seems like it has some weird changes in it - any idea what those are?

**Comment by ygannett** [comment]
@rbayliss  It seems merging `develop` didn't go well and caused unrelated file changes were indicated in this branch.  I reverted the branch to the commit before the merge, then merged the latest (as of Aug. 6th) `develop` into the branch.

**Review by rbayliss — APPROVED** [review]
This looks good to me.  I did some testing on the Drupal side, and things are looking good on org pages, location listing pages, and location pages.  I'm removing the comment about `raw` being necessary here, because it seems like it isn't true in this case.

**Review by yriahi — APPROVED** [review]
looks good to me

**Pull request merged**
