### PR TITLE
Refactor `TabContainer` global calls

### PR DESCRIPTION
**Pull request by bronzehedwick**
## Description
Switch to `globalThis` instead of using the Node only `global`, the browser only `window`, or relying on transpiling. This keeps global value access consistent across environments.

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis

This fixes fatal errors in either the server environment or the browser, depending on which global is chosen.

## Related Issue / Ticket
n/a

## Steps to Test

1. Checkout the PR locally
2. Link Mayflower React to a site that does both SSR and browser rendering of `<TabContainer>` and `<Tab>`.
3. Observe there are no fatal build errors

### CODE REVIEW

**Comment by clairesunstudio** [comment]
Eslint is throwing some errors https://app.circleci.com/pipelines/github/massgov/mayflower/5046/workflows/3df436b5-fee0-408d-82c1-98194f76da77/jobs/54022/parallel-runs/0/steps/0-106

Might need to upgrade eslint?

**Comment by clairesunstudio** [comment]
Please add a changelog

**Comment by bronzehedwick** [comment]
Hey @clairesunstudio, thanks for the feedback!

> Eslint is throwing some errors https://app.circleci.com/pipelines/github/massgov/mayflower/5046/workflows/3df436b5-fee0-408d-82c1-98194f76da77/jobs/54022/parallel-runs/0/steps/0-106
> 
> Might need to upgrade eslint?

These errors are present in the `develop` branch.

<details><summary>Lint log on develop branch</summary>

```
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean
mayflower» cd packages/react/
react» npm run lint

> @massds/mayflower-react@10.4.0 lint
> eslint . -c .eslintrc.json


/Users/chris/Sites/Lullabot/mayflower/packages/react/src/components/atoms/buttons/ButtonWithIcon/index.js
  71:23  warning  Prop type "object" is forbidden  react/forbid-prop-types

/Users/chris/Sites/Lullabot/mayflower/packages/react/src/components/forms/FeedbackForm/index.js
  34:25  warning  Prop type "any" is forbidden  react/forbid-prop-types

/Users/chris/Sites/Lullabot/mayflower/packages/react/src/components/forms/InputTextFuzzy/index.js
  224:3  warning  Prop type "object" is forbidden  react/forbid-prop-types

/Users/chris/Sites/Lullabot/mayflower/packages/react/src/components/molecules/Breadcrumb/item.js
  8:24  warning  'currentPage' is missing in props validation  react/prop-types

/Users/chris/Sites/Lullabot/mayflower/packages/react/src/components/molecules/HamburgerNav/index.js
  109:11  warning  'overlayOffset' is assigned a value but never used  no-unused-vars

/Users/chris/Sites/Lullabot/mayflower/packages/react/src/components/molecules/HeaderNav/index.js
  155:17  warning  'children' is missing in props validation  react/prop-types
  162:35  warning  'narrow' is missing in props validation    react/prop-types

/Users/chris/Sites/Lullabot/mayflower/packages/react/src/components/molecules/HeaderNav/main-nav.js
  56:3  warning  'active' is missing in props validation  react/prop-types

/Users/chris/Sites/Lullabot/mayflower/packages/react/src/components/organisms/Header/utility-items.js
  193:77  warning  Do not use Array index in keys   react/no-array-index-key
  211:3   warning  Prop type "object" is forbidden  react/forbid-prop-types
  232:7   warning  Prop type "object" is forbidden  react/forbid-prop-types

/Users/chris/Sites/Lullabot/mayflower/packages/react/src/components/organisms/LinkList/index.js
  51:22  warning  Do not use Array index in keys  react/no-array-index-key

/Users/chris/Sites/Lullabot/mayflower/packages/react/src/components/organisms/PageHeaderAddons/index.js
  11:8  warning  'PublishState' is defined but never used  no-unused-vars

✖ 13 problems (0 errors, 13 warnings)
```

</details>

I can fix these as part of this branch.

> Please add a changelog

Done!

**Comment by clairesunstudio** [comment]
thanks! oh I mean the ones related to `globalThis`
Screen Shot 2023-05-16 at 5 13 45 PM

**Comment by clairesunstudio** [comment]
thanks! oh I mean the ones related to `globalThis`
Screen Shot 2023-05-16 at 5 13 45 PM

**Comment by clairesunstudio** [comment]
thanks! oh I mean the ones related to `globalThis`
Screen Shot 2023-05-16 at 5 13 45 PM

**Comment by bronzehedwick** [comment]
> thanks! oh I mean the ones related to `globalThis`

Ah got it! I'll address that one as well.

**Comment by clairesunstudio** [comment]
These CircleCI failures are not related to this PR but will block release. Still looking into the issues

**Comment by clairesunstudio** [comment]
"The error I see in CircleCI is "The user who triggered the build may not have permission to a context being used."So it is somehow permissions related" 
This might be because @bronzehedwick is not part of the org. I will bypass these failures for now.

**Review by clairesunstudio — APPROVED** [review]

**Pull request merged**
