### PR TITLE
Dp 21345 add button with icon to core

### PR DESCRIPTION
**Pull request by clairesunstudio**
Fixed button with icon styling for all variants, and added examples to core documentation

Screen Shot 2022-03-16 at 4 36 58 PM

https://mayflower.digital.mass.gov/core/b/DP-21345-add-button-with-icon-to-core

### CODE REVIEW

**Comment by clairesunstudio** [comment]
React backstop failing on the arrow buttons missing drop shadow
https://46635-137521197-gh.circle-artifacts.com/0/backstop/data/html_report/index.html

**Comment by clairesunstudio** [comment]
patternlab backstop is approved in the base branch

**Review by ygannett — COMMENTED** [review]
It looks good.  I suggest adding `focusable="false"` to avoid any focus issues with IE and Edge:  https://a11y-guidelines.orange.com/en/articles/accessible-svg/

Another thing, for the see more buttons, I suggest adding room for context info for screen reader users:  "See more **of WHAT**."
The contextual info might not be necessary based on how the buttons are used.  So, adding it could be optional.  It's up to you to use `aria-lable` or add visually hidden text after "See More."

```
<button class="ma__button ma__button--c-white" type="" href="">
  <span>See More</span>
  <svg
    aria-hidden="true"
    width="1em"
    height="1em"
    viewBox="0 0 59 38"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      d="M29.414 37.657L.344 8.586 8.828.102l20.586 20.584L50 .1l8.484 8.485-29.07 29.072"
    ></path>
  </svg>
</button>
```

**Comment by clairesunstudio** [comment]
thanks @ygannett, updated the doc based on your comments

**Pull request merged**
