### PR TITLE
remove unused pilot theme

### PR DESCRIPTION
**Pull request by clairesunstudio**
clean up unused pilot theme compilation

### CODE REVIEW

**Review by mrossi113 — APPROVED** [review]
👍 LGTM! @clairesunstudio see my comment.

**Comment by mrossi113** [comment]
@clairesunstudio in this PR do you want to clean up the `Go to classic Mass.gov`as well? That was from pilot.mass.gov in the header of each twig.
```
{% if not hideBackTo %}
<div class="ma__header__backto">
    <a href="http://www.mass.gov">Go to classic Mass.gov</a>
</div>
{% endif %}
```

**Review by rbayliss — APPROVED** [review]
Looks good to me!

**Comment by clairesunstudio** [comment]
@mrossi113 i can address that in a separate pr. I think we can keep that header back to button but just not render it by passing `hideBackTo = true`. What do you think?

**Comment by mrossi113** [comment]
Discussed with @clairesunstudio about the `Go to classic Mass.gov` this will be handled in another ticket. By keeping the functionality, but changing the text in the link.

**Pull request merged**
